/*                   This file is part of m2tom3
       (C) 1991-1994 Lehrstuhl fuer Informatik III, RWTH Aachen
                         All Rights Reserved
*/

Module          ("Configuration")
Module          ("Message")
