---
name: Check latest
# Build and test starting from latest binary release.

on:
  pull_request: {branches: master}
  push:

concurrency: ci

jobs:
  linux-integration:
    uses: modula3/cm3/.github/workflows/linux-integration-from-binary.yml@master
    with:
      os: ubuntu-latest
      cm3build: cm3-min-AMD64_LINUX-d5.11.3-Linux5.4.0-20211008.tar.gz

  macos-integration:
    uses: modula3/cm3/.github/workflows/macos-integration-from-binary.yml@master
    with:
      os: macos-latest

#  mingw-integration:
#    uses: modula3/cm3/.github/workflows/mingw-integration-from-binary.yml@master
#    with:
#      os: windows-latest

  win32-integration:
    uses: modula3/cm3/.github/workflows/win32-integration-from-binary.yml@master
    with:
      os: windows-latest
