---
name: Check latest
# Build and test starting from latest bootstrap release.

on:
  pull_request: {branches: master}
  push:

concurrency: ci

jobs:
  linux-integration:
    uses: modula3/cm3/.github/workflows/linux-integration-from-bootstrap.yml@master

  macos-integration:
    uses: modula3/cm3/.github/workflows/macos-integration-from-bootstrap.yml@master

  mingw-integration:
    uses: modula3/cm3/.github/workflows/mingw-integration-from-bootstrap.yml@master

  win32-integration:
    uses: modula3/cm3/.github/workflows/windows-integration-from-binary.yml@master
    with:
      os: windows-latest
      target: I386_NT
      backend: >-
        ["c", "integrated"]

  win64-integration:
    uses: modula3/cm3/.github/workflows/win64-integration-from-bootstrap.yml@master
