---
name: Check latest
# Build and test starting from latest bootstrap release.

on:
  pull_request: {branches: master}
  push:

concurrency: ci

jobs:
#  linux-integration:
#    uses: modula3/cm3/.github/workflows/posix-integration-from-bootstrap.yml@master
#    with:
#      os: ubuntu-latest

#  macos-integration:
#    uses: modula3/cm3/.github/workflows/posix-integration-from-bootstrap.yml@master
#    with:
#      os: macos-latest

#  mingw-integration:
#    uses: modula3/cm3/.github/workflows/mingw-integration-from-bootstrap.yml@master

#  windows-integration:
#    uses: modula3/cm3/.github/workflows/windows-integration-from-bootstrap.yml@master

  I386_LINUX:
    uses: coder5506/cm3/.github/workflows/i386-linux-integration.yml@master
